title: Jekyll Play
email: budhram.gurung01@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  The minimal Jekyll base template to quickly start with.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
image_base_url: /assets/img
twitter_username: coolbrg
github_username:  coolbrg

google_analytics: # your google analytics id

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true
